// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMB8r231BJbj9MsH5mYlgnEeSpXn9C7w',
    appId: '1:972590109607:android:fad68d48449c979cb31c82',
    messagingSenderId: '972590109607',
    projectId: 'abhiroop43-fl-exp-trck',
    storageBucket: 'abhiroop43-fl-exp-trck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsDV405fdoO38U9NMDT4q_wWk_i9zzNI',
    appId: '1:972590109607:ios:fecf2f26d4e00945b31c82',
    messagingSenderId: '972590109607',
    projectId: 'abhiroop43-fl-exp-trck',
    storageBucket: 'abhiroop43-fl-exp-trck.firebasestorage.app',
    androidClientId:
        '972590109607-8btn2esjnrcp999fu5ufcsm3sjvu8jg7.apps.googleusercontent.com',
    iosClientId:
        '972590109607-nb2olk8cfoitknjsg2rf8m713ftn07rp.apps.googleusercontent.com',
    iosBundleId: 'dev.abhiroopsantra.flutterExpenseTracker',
  );
}
